### PR TITLE
Create simple_calculator.cpp

### PR DESCRIPTION
**Pull request by jindalmayank13**

### CODE REVIEW

**Comment by jindalmayank13** [comment]
Maam has this pull request of simple calculator been approved?

**Comment by Srishti44-g** [comment]
yes!!

**Comment by jindalmayank13** [comment]
but i have also made 4 other pull requests in different repositories and they have been approved ,so those four are in waiting on hactoberfest site. Will this calculator one be counted after this or not?

**Comment by Srishti44-g** [comment]
the first four will be considered

**Pull request merged**
